import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';import { ContextoUsuarioService } from '../contexto-usuario/contexto-usuario.service';import { JsonDatabaseService } from '../database/json-database.service';
@Injectable() export class PropostaService{constructor(private db:JsonDatabaseService,private ctx:ContextoUsuarioService){}
private async enrich(p:any){return{...p,pedido:await this.db.findById<any>('pedidos',p.idPedido),usina:await this.db.findById<any>('usinas',p.idUsina)}}
async criar(dto:any,user:any){const idUsina=await this.ctx.obterUsinaId(user.sub);if(await this.db.findOne<any>('bloqueios-usina',b=>String(b.idUsina)===String(idUsina)&&b.ativo))throw new ForbiddenException('Usina bloqueada.');const pedido:any=await this.db.findById('pedidos',dto.idPedido||dto.pedidoId||dto.solicitacaoId);if(!pedido||!['aberto','em_negociacao'].includes(pedido.status))throw new BadRequestException('Pedido indisponivel.');if(await this.db.findOne<any>('propostas',p=>String(p.idPedido)===String(pedido.idPedido)&&String(p.idUsina)===String(idUsina)&&p.status!=='cancelada'))throw new ConflictException('Ja existe proposta desta usina para este pedido.');const prop=await this.db.create<any>('propostas',{idProposta:this.db.newId(),idPedido:pedido.idPedido,idUsina,idUsuarioResponsavel:user.sub,valor:+dto.valor||dto.valor,prazo:dto.prazo,observacao:dto.observacao,status:'enviada',dataEnvio:new Date().toISOString()});if(pedido.status==='aberto')await this.db.update('pedidos',pedido.idPedido,{status:'em_negociacao'});return prop;}
async recebidas(user:any){const idEmpresa=await this.ctx.obterEmpresaId(user.sub);const pedidos=await this.db.filter<any>('pedidos',p=>String(p.idEmpresaCompradora)===String(idEmpresa));const ids=new Set(pedidos.map(p=>String(p.idPedido)));return Promise.all((await this.db.filter<any>('propostas',p=>ids.has(String(p.idPedido))&&p.status!=='cancelada')).map(p=>this.enrich(p)))}
async enviadas(user:any){const idUsina=await this.ctx.obterUsinaId(user.sub);return Promise.all((await this.db.filter<any>('propostas',p=>String(p.idUsina)===String(idUsina))).map(p=>this.enrich(p)))}
async detalhe(id:any,user:any){const p:any=await this.db.findById('propostas',String(id));if(!p)throw new NotFoundException('Proposta não encontrada.');const ep=await this.enrich(p);if(user.tipoUsuario?.includes('empresa')&&String(ep.pedido?.idEmpresaCompradora)!==String(await this.ctx.obterEmpresaId(user.sub)))throw new ForbiddenException();if(user.tipoUsuario?.includes('usina')&&String(p.idUsina)!==String(await this.ctx.obterUsinaId(user.sub)))throw new ForbiddenException();return ep;}
async aceitar(id:any,user:any){const p=await this.detalhe(id,user);const all=await this.db.readAll<any>('propostas');for(const x of all)if(String(x.idPedido)===String(p.idPedido))x.status='recusada';const idx=all.findIndex(x=>String(x.idProposta)===String(p.idProposta)||String(x.id)===String(id));all[idx].status='aceita';await this.db.replaceAll('propostas',all);await this.db.update('pedidos',p.idPedido,{status:'proposta_aceita',valorTotal:p.valor});return all[idx];}
async recusar(id:any,user:any){await this.detalhe(id,user);return this.db.update<any>('propostas',String(id),{status:'recusada'})} async cancelar(id:any,user:any){await this.detalhe(id,user);return this.db.update<any>('propostas',String(id),{status:'cancelada'})} }
